---
# Ansible playbook to configure hosts for k3d, docker-engine,
# and go dev of gitops-toolkit
# ansible-galaxy install -r requirements.yml
# ansible-playbook -i localhost, -c local --tags setup playbook.yml
# note: some tasks require sudo perms
- hosts: all
  tags:
    - docker
  roles:
    - andrewrothstein.docker_engine
    - andrewrothstein.k3d
    - andrewrothstein.kubectl
    - andrewrothstein.k9s
    - andrewrothstein.argocd
- hosts: all
  tags:
    - go
  vars:
    go_dev_install:
      - pkg: google.golang.org/protobuf/cmd/protoc-gen-go@latest
        target: protoc-gen-go
      - pkg: google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        target: protoc-gen-go-grpc
  roles:
    - andrewrothstein.protoc
    - andrewrothstein.goreleaser
    - andrewrothstein.go-dev
